name: The Future Of
favicon: null
layout_spectrum: 0.9753969009034336
typography_spectrum: 0.47613984323106706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6914575616829097
  lightness: 0.03563132812269032
  saturation: 0.24650059081614017
  rhythmicContrast: 0.1304498529061675
purpose: []
