name: THE FUTURE OF
favicon: null
layout_spectrum: 0.45417
typography_spectrum: 0.51161
title: THE FUTURE OF
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#effcfc'
    - '#b4d6da'
    - '#95bec6'
    - '#77a3aa'
    - '#5d838c'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
